% [Modeling]离散形式的阻滞增长模型y(n)=y(n-1)*(1+a-y(n-1))中a对其变化趋势的影响
% Example145_logistic(0.1, 1, 60);
% % 单增序列,有极限
% Example145_logistic(0.1, 1.8, 60);
% % 震荡序列,有极限
% Example145_logistic(0.1, 2.1, 60);
% % 震荡序列,双周期收敛
% Example145_logistic(0.1, 2.5, 60);
% % 震荡序列,多周期收敛
y=Example145_logistic(0.1, 1, 60);
h=plot(y, 'r-*');
grid on;
hm=uicontrol(gcf,'style','popupmenu',...
    'string',...
    'a = 1|a = 1.8|a = 2.1|a = 2.5',...
    'position',[250 20 50 20]);
set(hm,'value',1);
huidiao=[...
    'v=get(hm,''value'');,',...
    'switch v,',...
    'case 1,',...
    'delete(h),',...
    'y=Example145_logistic(0.1, 1, 60);,',...
    'h=plot(y, "r-*");,',...
    'grid on,',...
    'case 2,',...
    'delete(h),',...
    'y=Example145_logistic(0.1, 1.8, 60);,',...
    'h=plot(y, "r-*");,',...
    'grid on,',...
    'case 3,',...
    'delete(h),',...
    'y=Example145_logistic(0.1, 2.1, 60);,',...
    'h=plot(y, "r-*");,',...
    'grid on,',...
    'case 4,',...
    'delete(h),',...
    'y=Example145_logistic(0.1, 2.5, 60);,',...
    'h=plot(y, "r-*"),',...
    'grid on,',...
    'end'];
set(hm,'callback',huidiao);
set(gca,'position',[0.2 0.2 0.6 0.6]);
title(' logistic: y(n) = y(n-1)*(1+a-y(n-1))');
hold on;