% 主程序一,用于展示各目标区域具体图形
%  -*- coding: utf-8 -*-
% running successfully on Ubuntu18.04.2 MATLAB R2018b
clear;clf;
d = 66.04; h = 115.20; r = 110.613;
staus = 10; i = 6; % staus的i次方个点
Ax = 800; % x坐标的放大倍数
Ay = 800; % y坐标的放大倍数
point = staus.^i; % 模拟的随机点数
RandData = rand(2,point);
x = Ax*(RandData(1,:)-0.5);
y = Ay*(RandData(2,:));
% scatter(x, y, 'r+');
hold on;
Definition;
Find_Area;

% ROI = [KickDn_1_Can, KickDn_2_Can, KickDn_3_Can, KickDn_8_Can, KickDn_9_Can, KickDn_10_Can];
% ROIData = RandData(:, ROI);
% scatter(Ax*(ROIData(1,:)-0.5), Ay*(ROIData(2,:)),'r*');

% KickDn_0_Area = KickDn_0_Can;  KickDn_0_Data = RandData(:, KickDn_0_Area);
% scatter(Ax*(KickDn_0_Data(1,:)-0.5), Ay*(KickDn_0_Data(2,:)),'r*');
% hold on;

subplot(2, 3, 1);
KickDn_1_Area = KickDn_1_Can;  KickDn_1_Data = RandData(:, KickDn_1_Area);
scatter(Ax*(KickDn_1_Data(1,:)-0.5), Ay*(KickDn_1_Data(2,:)),'k*');
hold on;
subplot(2, 3, 2);
KickDn_2_Area = KickDn_2_Can;  KickDn_2_Data = RandData(:, KickDn_2_Area);
scatter(Ax*(KickDn_2_Data(1,:)-0.5), Ay*(KickDn_2_Data(2,:)),'k*');
hold on;
subplot(2, 3, 3);
KickDn_3_Area = KickDn_3_Can;  KickDn_3_Data = RandData(:, KickDn_3_Area);
scatter(Ax*(KickDn_3_Data(1,:)-0.5), Ay*(KickDn_3_Data(2,:)),'k*');
hold on;
subplot(2, 3, 4);
KickDn_8_Area = KickDn_8_Can;  KickDn_8_Data = RandData(:, KickDn_8_Area);
scatter(Ax*(KickDn_8_Data(1,:)-0.5), Ay*(KickDn_8_Data(2,:)),'k*');
hold on;
subplot(2, 3, 5);
KickDn_9_Area = KickDn_9_Can;  KickDn_9_Data = RandData(:, KickDn_9_Area);
scatter(Ax*(KickDn_9_Data(1,:)-0.5), Ay*(KickDn_9_Data(2,:)),'k*');
hold on;
subplot(2, 3, 6);
KickDn_10_Area = KickDn_10_Can;KickDn_10_Data = RandData(:, KickDn_10_Area);
scatter(Ax*(KickDn_10_Data(1,:)-0.5), Ay*(KickDn_10_Data(2,:)),'k*');



% 主程序二,用于计算概率,结果保存在当前目录下tp.txt文件中
%  -*- coding: utf-8 -*-
% running successfully on Ubuntu18.04.2 MATLAB R2018b
for i=1:10
    clear;clf;
    fid = fopen('tp.txt','at');
    d = 66.04; h = 115.20; r = 110.613;
    N = 100000; 
    disp(["Times of experiment:", N]);
    mu = [0 0];
    sigma = [100000 0; 0 9000];
    RandData = mvnrnd(mu, sigma, N);
    RandData = RandData';
    x = RandData(1, :);
    y = abs(RandData(2, :))+r;
    scatter(RandData(1, :), y,'k');
    axis equal;
    hold on;
    Definition;
    Find_Area;

    % ROI = KickDn_1_Can; % 寻找位于目标区域的散点
    % ROIData = RandData(:, ROI);
    % 
    % plot(ROIData(1,:), abs(ROIData(2,:)) + r,'k*');
    % Probability = length(ROI)/length(RandData);
    % disp("Probility = ");disp(Probability); 

    KickDn_1_Area = KickDn_1_Can;  KickDn_1_Data = RandData(:, KickDn_1_Area);
    Probability_KickDn_1 = length(KickDn_1_Area)/length(RandData);
    scatter(KickDn_1_Data(1, :), abs(KickDn_1_Data(2,:))+r,'r');
    disp(["Probability_KickDn_1  = ", Probability_KickDn_1]);
    KickDn_2_Area = KickDn_2_Can;  KickDn_2_Data = RandData(:, KickDn_2_Area);
    Probability_KickDn_2 = length(KickDn_2_Area)/length(RandData);
    scatter(KickDn_2_Data(1, :), abs(KickDn_2_Data(2,:))+r,'r');
    disp(["Probability_KickDn_2  = ", Probability_KickDn_2]);
    KickDn_3_Area = KickDn_3_Can;  KickDn_3_Data = RandData(:, KickDn_3_Area);
    Probability_KickDn_3 = length(KickDn_3_Area)/length(RandData);
    scatter(KickDn_3_Data(1, :), abs(KickDn_3_Data(2,:))+r,'r');
    disp(["Probability_KickDn_3  = ", Probability_KickDn_3]);
    KickDn_8_Area = KickDn_8_Can;  KickDn_8_Data = RandData(:, KickDn_8_Area);
    Probability_KickDn_8 = length(KickDn_8_Area)/length(RandData);
    scatter(KickDn_8_Data(1, :), abs(KickDn_8_Data(2,:))+r,'r');
    disp(["Probability_KickDn_8  = ", Probability_KickDn_8]);
    KickDn_9_Area = KickDn_9_Can;  KickDn_9_Data = RandData(:, KickDn_9_Area);
    Probability_KickDn_9 = length(KickDn_9_Area)/length(RandData);
    scatter(KickDn_9_Data(1, :), abs(KickDn_9_Data(2,:))+r,'r');
    disp(["Probability_KickDn_9  = ", Probability_KickDn_9]);
    KickDn_10_Area = KickDn_10_Can;KickDn_10_Data = RandData(:, KickDn_10_Area);
    Probability_KickDn_10 = length(KickDn_10_Area)/length(RandData);
    scatter(KickDn_10_Data(1, :), abs(KickDn_10_Data(2,:))+r,'r');
    disp(["Probability_KickDn_10 = ", Probability_KickDn_10]);

    disp(["Probability_award_100 = ", Probability_KickDn_10]);
    disp(["Probability_award_20  = ", Probability_KickDn_9+Probability_KickDn_2]);
    disp(["Probability_award_10  = ", Probability_KickDn_3+Probability_KickDn_8]);
    disp(["Probability_award_30  = ", Probability_KickDn_1]);
    disp(["Probability_award>=10 = ", Probability_KickDn_10+Probability_KickDn_9+Probability_KickDn_2+Probability_KickDn_3+Probability_KickDn_8+Probability_KickDn_1])
    
    fprintf(fid,'%f %f %f %f %f %f %f %f %f\n',...
        Probability_KickDn_1, Probability_KickDn_2,...
        Probability_KickDn_3, Probability_KickDn_8,...
        Probability_KickDn_9, Probability_KickDn_10,...
        Probability_KickDn_1+Probability_KickDn_9+Probability_KickDn_2+Probability_KickDn_10,...
        Probability_KickDn_3+Probability_KickDn_8,...
        1-(Probability_KickDn_10+Probability_KickDn_9+Probability_KickDn_2+Probability_KickDn_3+Probability_KickDn_8+Probability_KickDn_1));
    fclose(fid);
    clc;
end
clc;


% 子程序一,定义易拉罐断电以及分别击中每个易拉罐的区域约束条件,不可单独运行,在主程序中调用
%  -*- coding: utf-8 -*-
Can11 = [-2*d, 0;
           -d, 0;
         -2*d, h;
           -d, h];
Can12 = [-d, 0;
          0, 0;
         -d, h;
          0, h];
Can13 = [ 0, 0;
          d, 0;
          0, h;
          d, h];
Can14 = [   d, 0;
          2*d, 0;
            d, h;
          2*d, h];
Can21 = [-1.5*d, h;
         -0.5*d, h;
         -1.5*d, 2*h;
         -0.5*d, 2*h];
Can22 = [-0.5*d, h;
          0.5*d, h;
         -0.5*d, 2*h;
          0.5*d, 2*h];
Can23 = [0.5*d, h;
         1.5*d, h;
         0.5*d, 2*h;
         1.5*d, 2*h];
Can31 = [-d, 2*h;
          0, 2*h;
         -d, 3*h;
          0, 3*h];
Can32 = [0, 2*h;
         d, 2*h;
         0, 3*h;
         d, 3*h];
Can41 = [-0.5*d, 3*h;
          0.5*d, 3*h;
         -0.5*d, 4*h;
          0.5*d, 4*h];
kick_dn_11_area = (((x-Can11(1, 1)).^2+(y-Can11(1, 2)).^2<r^2)...
                  |((x-Can11(2, 1)).^2+(y-Can11(2, 2)).^2<r^2)...
                  |((x-Can11(3, 1)).^2+(y-Can11(3, 2)).^2<r^2)...
                  |((x-Can11(4, 1)).^2+(y-Can11(4, 2)).^2<r^2)...
                  |(x>Can11(1,1)&x<Can11(2,1)&y<Can11(1,2)&y+r>Can11(1,2))...
                  |(x>Can11(3,1)&x<Can11(4,1)&y<Can11(3,2)+r&y>Can11(3,2))...
                  |(x>Can11(1,1)-r&x<Can11(1,1)&y<Can11(3,2)&y>Can11(1,2))...
                  |(x>Can11(2,1)&x<Can11(2,1)+r&y<Can11(4,2)&y>Can11(2,2)));
kick_dn_12_area = (((x-Can12(1, 1)).^2+(y-Can12(1, 2)).^2<r^2)...
                  |((x-Can12(2, 1)).^2+(y-Can12(2, 2)).^2<r^2)...
                  |((x-Can12(3, 1)).^2+(y-Can12(3, 2)).^2<r^2)...
                  |((x-Can12(4, 1)).^2+(y-Can12(4, 2)).^2<r^2)...
                  |(x>Can12(1,1)&x<Can12(2,1)&y<Can12(1,2)&y+r>Can12(1,2))...
                  |(x>Can12(3,1)&x<Can12(4,1)&y<Can12(3,2)+r&y>Can12(3,2))...
                  |(x>Can12(1,1)-r&x<Can12(1,1)&y<Can12(3,2)&y>Can12(1,2))...
                  |(x>Can12(2,1)&x<Can12(2,1)+r&y<Can12(4,2)&y>Can12(2,2)));
kick_dn_13_area = (((x-Can13(1, 1)).^2+(y-Can13(1, 2)).^2<r^2)...
                  |((x-Can13(2, 1)).^2+(y-Can13(2, 2)).^2<r^2)...
                  |((x-Can13(3, 1)).^2+(y-Can13(3, 2)).^2<r^2)...
                  |((x-Can13(4, 1)).^2+(y-Can13(4, 2)).^2<r^2)...
                  |(x>Can13(1,1)&x<Can13(2,1)&y<Can13(1,2)&y+r>Can13(1,2))...
                  |(x>Can13(3,1)&x<Can13(4,1)&y<Can13(3,2)+r&y>Can13(3,2))...
                  |(x>Can13(1,1)-r&x<Can13(1,1)&y<Can13(3,2)&y>Can13(1,2))...
                  |(x>Can13(2,1)&x<Can13(2,1)+r&y<Can13(4,2)&y>Can13(2,2)));           
kick_dn_14_area = (((x-Can14(1, 1)).^2+(y-Can14(1, 2)).^2<r^2)...
                  |((x-Can14(2, 1)).^2+(y-Can14(2, 2)).^2<r^2)...
                  |((x-Can14(3, 1)).^2+(y-Can14(3, 2)).^2<r^2)...
                  |((x-Can14(4, 1)).^2+(y-Can14(4, 2)).^2<r^2)...
                  |(x>Can14(1,1)&x<Can14(2,1)&y<Can14(1,2)&y+r>Can14(1,2))...
                  |(x>Can14(3,1)&x<Can14(4,1)&y<Can14(3,2)+r&y>Can14(3,2))...
                  |(x>Can14(1,1)-r&x<Can14(1,1)&y<Can14(3,2)&y>Can14(1,2))...
                  |(x>Can14(2,1)&x<Can14(2,1)+r&y<Can14(4,2)&y>Can14(2,2)));              
kick_dn_21_area = (((x-Can21(1, 1)).^2+(y-Can21(1, 2)).^2<r^2)...
                  |((x-Can21(2, 1)).^2+(y-Can21(2, 2)).^2<r^2)...
                  |((x-Can21(3, 1)).^2+(y-Can21(3, 2)).^2<r^2)...
                  |((x-Can21(4, 1)).^2+(y-Can21(4, 2)).^2<r^2)...
                  |(x>Can21(1,1)&x<Can21(2,1)&y<Can21(1,2)&y+r>Can21(1,2))...
                  |(x>Can21(3,1)&x<Can21(4,1)&y<Can21(3,2)+r&y>Can21(3,2))...
                  |(x>Can21(1,1)-r&x<Can21(1,1)&y<Can21(3,2)&y>Can21(1,2))...
                  |(x>Can21(2,1)&x<Can21(2,1)+r&y<Can21(4,2)&y>Can21(2,2)));              
kick_dn_22_area = (((x-Can22(1, 1)).^2+(y-Can22(1, 2)).^2<r^2)...
                  |((x-Can22(2, 1)).^2+(y-Can22(2, 2)).^2<r^2)...
                  |((x-Can22(3, 1)).^2+(y-Can22(3, 2)).^2<r^2)...
                  |((x-Can22(4, 1)).^2+(y-Can22(4, 2)).^2<r^2)...
                  |(x>Can22(1,1)&x<Can22(2,1)&y<Can22(1,2)&y+r>Can22(1,2))...
                  |(x>Can22(3,1)&x<Can22(4,1)&y<Can22(3,2)+r&y>Can22(3,2))...
                  |(x>Can22(1,1)-r&x<Can22(1,1)&y<Can22(3,2)&y>Can22(1,2))...
                  |(x>Can22(2,1)&x<Can22(2,1)+r&y<Can22(4,2)&y>Can22(2,2)));              
kick_dn_23_area = (((x-Can23(1, 1)).^2+(y-Can23(1, 2)).^2<r^2)...
                  |((x-Can23(2, 1)).^2+(y-Can23(2, 2)).^2<r^2)...
                  |((x-Can23(3, 1)).^2+(y-Can23(3, 2)).^2<r^2)...
                  |((x-Can23(4, 1)).^2+(y-Can23(4, 2)).^2<r^2)...
                  |(x>Can23(1,1)&x<Can23(2,1)&y<Can23(1,2)&y+r>Can23(1,2))...
                  |(x>Can23(3,1)&x<Can23(4,1)&y<Can23(3,2)+r&y>Can23(3,2))...
                  |(x>Can23(1,1)-r&x<Can23(1,1)&y<Can23(3,2)&y>Can23(1,2))...
                  |(x>Can23(2,1)&x<Can23(2,1)+r&y<Can23(4,2)&y>Can23(2,2)));              
kick_dn_31_area = (((x-Can31(1, 1)).^2+(y-Can31(1, 2)).^2<r^2)...
                  |((x-Can31(2, 1)).^2+(y-Can31(2, 2)).^2<r^2)...
                  |((x-Can31(3, 1)).^2+(y-Can31(3, 2)).^2<r^2)...
                  |((x-Can31(4, 1)).^2+(y-Can31(4, 2)).^2<r^2)...
                  |(x>Can31(1,1)&x<Can31(2,1)&y<Can31(1,2)&y+r>Can31(1,2))...
                  |(x>Can31(3,1)&x<Can31(4,1)&y<Can31(3,2)+r&y>Can31(3,2))...
                  |(x>Can31(1,1)-r&x<Can31(1,1)&y<Can31(3,2)&y>Can31(1,2))...
                  |(x>Can31(2,1)&x<Can31(2,1)+r&y<Can31(4,2)&y>Can31(2,2)));              
kick_dn_32_area = (((x-Can32(1, 1)).^2+(y-Can32(1, 2)).^2<r^2)...
                  |((x-Can32(2, 1)).^2+(y-Can32(2, 2)).^2<r^2)...
                  |((x-Can32(3, 1)).^2+(y-Can32(3, 2)).^2<r^2)...
                  |((x-Can32(4, 1)).^2+(y-Can32(4, 2)).^2<r^2)...
                  |(x>Can32(1,1)&x<Can32(2,1)&y<Can32(1,2)&y+r>Can32(1,2))...
                  |(x>Can32(3,1)&x<Can32(4,1)&y<Can32(3,2)+r&y>Can32(3,2))...
                  |(x>Can32(1,1)-r&x<Can32(1,1)&y<Can32(3,2)&y>Can32(1,2))...
                  |(x>Can32(2,1)&x<Can32(2,1)+r&y<Can32(4,2)&y>Can32(2,2)));              
kick_dn_41_area = (((x-Can41(1, 1)).^2+(y-Can41(1, 2)).^2<r^2)...
                  |((x-Can41(2, 1)).^2+(y-Can41(2, 2)).^2<r^2)...
                  |((x-Can41(3, 1)).^2+(y-Can41(3, 2)).^2<r^2)...
                  |((x-Can41(4, 1)).^2+(y-Can41(4, 2)).^2<r^2)...
                  |(x>Can41(1,1)&x<Can41(2,1)&y<Can41(1,2)&y+r>Can41(1,2))...
                  |(x>Can41(3,1)&x<Can41(4,1)&y<Can41(3,2)+r&y>Can41(3,2))...
                  |(x>Can41(1,1)-r&x<Can41(1,1)&y<Can41(3,2)&y>Can41(1,2))...
                  |(x>Can41(2,1)&x<Can41(2,1)+r&y<Can41(4,2)&y>Can41(2,2)));              


% 子程序二,用于寻找目标区域,不可单独运行,在主程序中调用
%  -*- coding: utf-8 -*-
KickDn_0_Can = find(y-r>0&(...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &~kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &~kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area))); 
% Award 100yuan=================
KickDn_10_Can = find(y-r>0&(...
            (kick_dn_11_area...
            &kick_dn_12_area...
            &kick_dn_13_area...
            &kick_dn_14_area))); 
% Award  20yuan=================
KickDn_9_Can = find(y-r>0&(...
            (~kick_dn_11_area...
            &kick_dn_12_area...
            &kick_dn_13_area...
            &kick_dn_14_area...
            &kick_dn_21_area...
            &kick_dn_22_area)|...
            (kick_dn_11_area...
            &kick_dn_12_area...
            &kick_dn_13_area...
            &~kick_dn_14_area...
            &kick_dn_21_area...
            &kick_dn_22_area...
            &kick_dn_23_area))); 
KickDn_2_Can = find(y-r>0&(...
            (~kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &kick_dn_31_area...
            &~kick_dn_32_area...
            &kick_dn_41_area)|...
            (~kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &~kick_dn_31_area...
            &kick_dn_32_area...
            &kick_dn_41_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &~kick_dn_21_area...
            &~kick_dn_22_area...
            &kick_dn_23_area...
            &~kick_dn_31_area...
            &kick_dn_32_area...
            &~kick_dn_41_area)|...
            (kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &~kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &kick_dn_14_area...
            &~kick_dn_21_area...
            &~kick_dn_22_area...
            &kick_dn_23_area...
            &~kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area))); 
% Award  10yuan=================        
KickDn_3_Can = find(y-r>0&(...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &~kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &kick_dn_31_area...
            &kick_dn_32_area...
            &kick_dn_41_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &kick_dn_21_area...
            &kick_dn_22_area...
            &~kick_dn_23_area...
            &kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &~kick_dn_21_area...
            &kick_dn_22_area...
            &kick_dn_23_area...
            &~kick_dn_31_area...
            &kick_dn_32_area...
            &~kick_dn_41_area)|...
            (kick_dn_11_area...
            &kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &~kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area)|...
            (~kick_dn_11_area...
            &kick_dn_12_area...
            &kick_dn_13_area...
            &~kick_dn_14_area...
            &~kick_dn_21_area...
            &kick_dn_22_area...
            &~kick_dn_23_area...
            &~kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &kick_dn_13_area...
            &kick_dn_14_area...
            &~kick_dn_21_area...
            &~kick_dn_22_area...
            &kick_dn_23_area...
            &~kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area))); 
KickDn_8_Can = find(y-r>0&(...
            (~kick_dn_11_area...
            &kick_dn_12_area...
            &kick_dn_13_area...
            &kick_dn_14_area...
            &~kick_dn_21_area...
            &kick_dn_31_area)|...
            (kick_dn_11_area...
            &kick_dn_12_area...
            &kick_dn_13_area...
            &~kick_dn_14_area...
            &~kick_dn_23_area...
            &kick_dn_32_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &kick_dn_13_area...
            &kick_dn_14_area...
            &kick_dn_21_area...
            &kick_dn_22_area)|...
            (kick_dn_11_area...
            &kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &kick_dn_22_area...
            &kick_dn_23_area))); 
% Award  30yuan=================           
KickDn_1_Can = find(y-r>0&(...
            (kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &~kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &~kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &~kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &~kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &~kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &~kick_dn_31_area...
            &~kick_dn_32_area...
            &kick_dn_41_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &kick_dn_14_area...
            &~kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &~kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &~kick_dn_21_area...
            &~kick_dn_22_area...
            &kick_dn_23_area...
            &~kick_dn_31_area...
            &~kick_dn_32_area...
            &~kick_dn_41_area)|...
            (~kick_dn_11_area...
            &~kick_dn_12_area...
            &~kick_dn_13_area...
            &~kick_dn_14_area...
            &~kick_dn_21_area...
            &~kick_dn_22_area...
            &~kick_dn_23_area...
            &~kick_dn_31_area...
            &kick_dn_32_area...
            &~kick_dn_41_area))); 
			
